src/about/urls.py
from django.urls import path
from . import views


app_name = 'about'


urlpatterns = [
    path('',views.aboutus , name='aboutus'),

]

src/agents/urls.py
from django.urls import path
from . import views


app_name = 'agents'


urlpatterns = [
    path('',views.agents_list , name='agent_list'),

]

src/contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'


urlpatterns = [
    path('' , views.send_mail , name='send_mail'),
    path('success/' , views.success , name='success'),
]

src/home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [
    path('' , views.home , name='home'),

]

src/project/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls' , namespace='home')),
    path('property/', include('property.urls' , namespace='property')),
    path('agents/', include('agents.urls' , namespace='agents')),
    path('about/', include('about.urls' , namespace='about')),
    path('contact/', include('contact.urls' , namespace='contact'))
]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "HOTEL RESERVATION ADMIN"
admin.site.site_title = "HOTEL RESERVATION ADMIN"
admin.site.site_index_title = "Welcome To Hotel Reservation Admin"

src/property/urls.py
from django.urls import path
from . import views


app_name = 'property'


urlpatterns = [
    path('',views.property_list , name='property_list'),
    path('<int:id>',views.property_detail , name='property_detail'),
]

src/about/models.py
from django.db import models

# Create your models here.


class About(models.Model):
    vision = models.TextField()
    mission = models.TextField()
    image = models.ImageField(upload_to='about/')

    def __str__(self):
        return str(self.id)

src/agents/models.py
from django.db import models

# Create your models here.


class Agent(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='agents/')


    def __str__(self):
        return self.name

src/contact/models.py
from django.db import models

# Create your models here.

class ContactDetails(models.Model):
    # location = 
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)


    def __str__(self):
        return str(self.id)

src/home/models.py
from django.db import models

# Create your models here.

src/property/models.py
from django.db import models
from location_field.models.plain import PlainLocationField
from django.contrib.gis.db import models

# Create your models here.

property_type = (
    ('sale' , "sale"),
    ('rent' , "rent")
)

class Property(models.Model):
    name = models.CharField(max_length=50)
    property_type = models.CharField(choices=property_type , max_length=10)
    price = models.PositiveIntegerField()
    category = models.ForeignKey('Category' ,null=True ,on_delete=models.SET_NULL)
    area = models.DecimalField(decimal_places=2 ,max_digits=8 )
    beds_number = models.PositiveIntegerField()
    baths_number = models.PositiveIntegerField()
    garages_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to='property/' , null=True)
    location = models.PointField()

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'


class Category(models.Model):
    category_name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='category/' , null=True)
    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'



class Reserve(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    notes  = models.TextField()

    def __str__(self):
        return self.name

src/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField()
    from_email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea , required=True)

src/property/forms.py
from django import forms
from .models import Reserve , Property


class ReserveForm(forms.ModelForm):
    class Meta : 
        model = Reserve
        fields = '__all__'

src/about/views.py
from django.shortcuts import render

# Create your views here.
from .models import About

def aboutus(request):
    about = About.objects.last()
    template = 'about/about.html'
    context = {
        'about' : about 
    }

    return render(request , template , context)

src/agents/views.py
from django.shortcuts import render
from .models import Agent
# Create your views here.

def agents_list(request):
    agent_list = Agent.objects.all()
    template = 'agents/agents.html'
    context = {
        'agent_list' : agent_list
    }

    return render(request , template , context)

src/contact/views.py
from django.shortcuts import render , redirect
from .forms import ContactForm
# Create your views here.
from .models import ContactDetails
from django.core.mail import  BadHeaderError
from django.core.mail import send_mail as sm
from django.http import HttpResponse , HttpResponseRedirect




def send_mail(request):
    contactdetails = ContactDetails.objects.last()
    template = 'contact/contact.html'

    if request.method == 'POST' : 
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            subject = contact_form.cleaned_data['subject']
            from_email = contact_form.cleaned_data['from_email']
            message = contact_form.cleaned_data['message']

            try : 
                sm(subject , message ,from_email , ['test@gmail.com'] )
            
            except BadHeaderError : 
                return HttpResponse('ivalid header')

            return redirect('contact:success')

    else:
        contact_form = ContactForm()


    context = {
        'contactdetails' : contactdetails  , 
        'contact_form' : contact_form
    }

    return render(request, template , context)


def success(request):
    return HttpResponse('Message Sent Successfully')

src/home/views.py
from django.shortcuts import render
from property.models import Property , Category
from agents.models import Agent
from django.db.models import Count
# Create your views here.


def home(request):
    category_list = Category.objects.annotate(property_count=Count('property')).values('category_name' , 'property_count' , 'image')
    print(category_list)
    property_list = Property.objects.all()
    agent_list = Agent.objects.all()
    template = 'home/home.html'
    context = {
        'category_list_home' : category_list ,
        'property_list_home' : property_list ,
        'agent_list_home' : agent_list
    }

    return render(request , template , context)

src/property/views.py
from django.shortcuts import render

# Create your views here.
from .models import Property , Category
from .forms import ReserveForm 
from django.db.models import Q

def property_list(request):
    property_list = Property.objects.all()
    template = 'property/list.html'

    address_query = request.GET.get('q')
    property_type = request.GET.getlist('property_type' , None)
    if address_query and property_type : 
        print(address_query)
        print(property_type)
        property_list = property_list.filter(
            Q(name__icontains = address_query) &
            Q(property_type__icontains=property_type[0])
        ).distinct()
        
    print(property_list)

    context = {
        'property_list' : property_list
    }

    return render(request , template , context)



def property_detail(request , id):
    property_detail = Property.objects.get(id=id)
    template = 'property/detail.html'


    if request.method == 'POST':
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()

    else:
        reserve_form = ReserveForm()


    context = {
        'property_detail' : property_detail , 
        'reserve_form' : reserve_form
    }

    return render(request , template , context)

src/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% get_media_prefix %}
{% block body %}
  

  
  <section class="probootstrap-slider flexslider">
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">

            <div class="probootstrap-home-search probootstrap-animate">
              <form action="{% url 'property:property_list' %}" method="get">
                <h2 class="heading">Search your next dream home here</h2>
                <div class="probootstrap-field-group">
                  <div class="probootstrap-fields">
                    
                    <div class="search-field">
                      <i class="icon-location2"></i>
                      <input type="text" name='q' class="form-control" placeholder="Enter address">
                    </div>
                    <div class="search-category">
                      <i class="icon-chevron-down"></i>
                      <select name="property_type" id="" class="form-control">
                        <option value="rent">For Rent</option>
                        <option value="sale">For Sale</option>
                      </select>
                    </div>
                  </div>
                  <button class="btn btn-success" type="submit"><i class="icon-magnifying-glass t2"></i> Start Search</button>
                </div>
              </form>
              <p class="mb0 text-left"><small>A free HTML5 template by <a href="https://uicookies.com/">uicookies.com</a> under license <a href="https://uicookies.com/license">Creative Commons 3.0</a></small> </p>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);" class="overlay"></li>
      <li style="background-image: url(img/slider_4.jpg);" class="overlay"></li>
      <li style="background-image: url(img/slider_2.jpg);" class="overlay"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="probootstrap-card text-center probootstrap-animate">
            <div class="probootstrap-card-media svg-sm colored">
              <img src="{% static 'img/flaticon/svg/001-prize.svg' %}" class="svg" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading">Award Winning Brooker</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <p><a href="#">Find out more</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-card text-center probootstrap-animate">
            <div class="probootstrap-card-media svg-sm colored">
              <img src="{% static 'img/flaticon/svg/005-new.svg' %}" class="svg" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading">New Houses</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <p><a href="#">Find out more</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-card text-center  probootstrap-animate">
            <div class="probootstrap-card-media svg-sm colored">
              <img src="{% static 'img/flaticon/svg/006-coin.svg' %}" class="svg" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading">Affordable Houses</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <p><a href="#">Find out more</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- END: section -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Explore Our Neighborhoods</h2>
      </div>
      <div class="row probootstrap-gutter10">
        {% for category_list in category_list_home %}

                                
          <div class="col-md-6 col-sm-6">
            <a href="#" class="probootstrap-hover-overlay">
              <img src="media/{{category_list.image}}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
              <div class="probootstrap-text-overlay">
                <h3>{{category_list.category_name}}</h3>
                <p>{{category_list.property_count}} Properties</p>
              </div>
            </a>
          </div>


        {% endfor %}

      </div>
    </div>
  </section>
  <!-- END: section -->

  <section class="probootstrap-section probootstrap-bg" style="background-image: url(img/slider_2.jpg);">
    <div class="container text-center probootstrap-animate" data-animate-effect="fadeIn">
      <h2 class="heading">Best Home &amp; Properties</h2>
      <p class="sub-heading">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
      <p><a href="#" class="btn btn-primary mb10">Find out more</a></p>
    </div>
  </section>
  <!-- END: section -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Featured Listing</h2>
      </div>
      <div class="row">
        {% for property in property_list_home %}
          

          <div class="col-md-4 col-sm-6">
            <div class="probootstrap-card probootstrap-listing">
              <div class="probootstrap-card-media">
                <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              </div>
              <div class="probootstrap-card-text">
                <h2 class="probootstrap-card-heading"><a href="#">{{property}}</a></h2>
                <div class="probootstrap-listing-location">
                  <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
                </div>
                <div class="probootstrap-listing-category for-sale"><span>for {{property.property_type}}</span></div>
                <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong> / month</div>
              </div>
              <div class="probootstrap-card-extra">
                <ul>
                  <li>
                    Area
                    <span>{{property.area}} m2</span>
                  </li>
                  <li>
                    Beds
                    <span>{{property.beds_number}}</span>
                  </li>
                  <li>
                    Baths
                    <span>{{property.baths_number}}</span>
                  </li>
                  <li>
                    Garages
                    <span>{{property.garages_number}}</span>
                  </li>
                </ul>
              </div>
            </div>
            <!-- END listing -->
          </div>

        {% endfor %}

      </div>
    </div>
  </section>


  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Services</h2>
      </div>
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-list2"></i></div>
            <h2 class="heading">Property Listing</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-power-cord"></i></div>
            <h2 class="heading">Property Management</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-price-tag2"></i></div>
            <h2 class="heading">Renting Properties</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-lg-block visible-md-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-direction"></i></div>
            <h2 class="heading">Selling Properties</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-home3"></i></div>
            <h2 class="heading">Brook A Property</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
          <div class="service text-center">
            <div class="icon"><i class="icon-magnifying-glass"></i></div>
            <h2 class="heading">Search Property</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          </div>
        </div>
        <div class="clearfix visible-lg-block visible-md-block"></div>
      </div>
    </div>
  </section>

  <!-- END: section -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Agents</h2>
      </div>
      <div class="row">
        
        {% for agent in agent_list_home %}
          

          
        <div class="col-md-3">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{{agent.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">{{agent}}</h2>
              <p><small>{{agent.name}}</small></p>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </section>
  {% endblock body %}

src/property/templates/property/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  

  
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

              <div class="page-title probootstrap-animate">
                  <div class="probootstrap-breadcrumbs">
                    <a href="#">Home</a><span><a href="{% url 'property:property_list' %}"> Properties </a></span>{{property_detail}}
                  </div>
                  <h1>{{property_detail}}</h1>
                </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Details</h2>

          <p>Type : {{property_detail.property_type}}</p>
          <p>Area : {{property_detail.area}} m2</p>
          <p>Beds : {{property_detail.beds_number}}</p>
          <p>Baths : {{property_detail.baths_number}}</p>
          <p>Garages : {{property_detail.garages_number}}</p>
        </div>
      </div>
    </div>
  </section>

  <section class="probootstrap-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>Reserve This Property</h2>
              <form action="" method="POST">
                {% csrf_token %}
                  {% bootstrap_form reserve_form %}
                  {% buttons %}
                      <button type="submit" class="btn btn-primary">Reserve</button>
                  {% endbuttons %}
              </form>
          </div>
        </div>
      </div>
    </section>


  {% endblock body %}

src/property/templates/property/list.html
{% extends 'base.html' %}

{% block body %}
  

  
  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
        {% if property_list %}
          
          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
              <div class="probootstrap-card probootstrap-listing">
                <div class="probootstrap-card-media">
                  <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
                </div>
                <div class="probootstrap-card-text">
                  <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.id %}">{{property}}</a></h2>
                  <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
                  </div>
                  <div class="probootstrap-listing-category for-sale"><span>for {{property.property_type}}</span></div>
                  <div class="probootstrap-listing-price"><strong>${{property.price}}</strong> / month</div>
                </div>
                <div class="probootstrap-card-extra">
                  <ul>
                    <li>
                      Area
                      <span>{{property.area}} m2</span>
                    </li>
                    <li>
                      Beds
                      <span>{{property.beds_number}}</span>
                    </li>
                    <li>
                      Baths
                      <span>{{property.baths_number}}</span>
                    </li>
                    <li>
                      Garages
                      <span>{{property.garages_number}}</span>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- END listing -->
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-10 col-sm-10">
            <h2>No Properties With This Name Or Type </h2>
          </div>
        {% endif %}

      </div>
    </div>
  </section>

  



  {% endblock body %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>uiCookies:Haus &mdash; Free Bootstrap Theme, Free Responsive Bootstrap Website Template</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="index.html" class="probootstrap-logo">Haus<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li {% if category_list_home %} class="active"{% endif %}><a href="/">Home</a></li>
            <li {% if property_list %} class="active"{% endif %}><a href="{% url 'property:property_list' %}">Properties</a></li>
            <li {% if agent_list %} class="active"{% endif %}><a href="{% url 'agents:agent_list' %}">Agents</a></li>
            <li {% if about %} class="active"{% endif %}><a href="{% url 'about:aboutus' %}">About</a></li>
            <li {% if contactdetails %} class="active"{% endif %}><a href="{% url 'contact:send_mail' %}">Contact</a></li>
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>


  
  {% block body %}
    
  {% endblock body %}
    

  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url(img/slider_3.jpg)">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">About Haus.</h4>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            <p><a href="#">Read more...</a></p>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Quick Links</h4>
            <ul class="stack-link">
              <li><a href="#">Property Listing</a></li>
              <li><a href="#">Rent Properties</a></li>
              <li><a href="#">Sell Properties</a></li>
              <li><a href="#">Agents</a></li>
              <li><a href="#">Testimonial</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Popular Cities</h4>
            <ul class="stack-link">
              <li><a href="#">New York <small>(320 properties)</small></a></li>
              <li><a href="#">San Francisco <small>(294 properties)</small></a></li>
              <li><a href="#">Brooklyn <small>(300 properties)</small></a></li>
              <li><a href="#">Chicago <small>(268 properties)</small></a></li>
              <li><a href="#">Los Angeles <small>(342 properties)</small></a></li>
            </ul>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Subscribe</h4>
            <p>Far far away behind the word mountains far from.</p>
            <form action="#">
              <div class="form-field">
                <input type="text" class="form-control" placeholder="Enter your email">
                <button class="btn btn-subscribe">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2017 <a href="https://uicookies.com/">uiCookies:Haus</a>. Designed by <a href="https://uicookies.com/">uicookies.com</a> <br> Demo Photos from <a href="https://pixabay.com/">Pixabay</a> &amp; <a href="https://unsplash.com/">Unsplash</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  

  <script src="{% static 'js/scripts.min.js' %}"></script>
  <script src="{% static 'js/main.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>